#!/bin/bash
cd "$(dirname "$0")"

echo - Importing sourcecode
cp -r src/* dist

echo - Compiling tsx
npx tsc dist/js/app.tsx --jsx preserve

echo - Merging
mkdir dist/jsTemp
mkdir dist/jsImport
cp -r dist/js dist/jsImport

cp dist/jsImport/js/app.jsx dist/jsTemp/app.jsx
rm dist/jsImport/js/app.jsx
cat dist/jsImport/**/*.jsx dist/jsTemp/app.jsx > dist/jsTemp/main_min.jsx

echo - Compiling jsx 
npx babel dist/jsTemp/main_min.jsx -d dist



echo - Merging CSS

cat dist/css/**/*.css > dist/main_min.css

echo - Cleaning up
rm -r dist/jsTemp
rm -r dist/jsImport
rm -r dist/js
rm -r dist/css


echo \|-------------------\|
echo \| Finished Building \|
echo \|-------------------\|